title: Corisca
owner_name: Napolean Bonparte Official
github_username: will-w-cheng, kinetekenergy, crownedbison, advikg
github_repo: "Corisca-Frontend"
baseurl: "/corsica-frontend"
remote_theme: jekyll/minima
minima:
  # social_links:
  #   - { platform: github, user_url: "https://github.com/nighthawkcoders"}
  #   - { platform: github, user_url: "https://github.com/Napoleon-Bonaparte-Official/corsica-frontend"}
  #   - { platform: github, user_url: "https://github.com/Napoleon-Bonaparte-Official/"}
# remote_theme: pages-themes/dinky@v0.2.0
# remote_theme: pages-themes/minimal@v0.2.0
# remote_theme: pages-themes/hacker@v0.2.0
# remote_theme: pages-themes/cayman@v0.2.0
# remote_theme: pages-themes/time-machine@v0.2.0
plugins:
- jekyll-remote-theme
future: true
