title: Corsica
owner_name: Napoléon Bonaparte Officiel
github_username: will-w-cheng, kinetekenergy, crownedbison, advikg
github_repo: "Corsica-Blog"
baseurl: "/corsica-blog"
remote_theme: jekyll/minima
plugins:
- jekyll-remote-theme
future: true
